#ifndef DEAMER_TEMPLATES_ANTLR_PARSER_PARSERDEFINITIONTEMPLATE_h
#define DEAMER_TEMPLATES_ANTLR_PARSER_PARSERDEFINITIONTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace deamer::templates::antlr::parser
{
	/*!	\class ParserDefinitionTemplate
	 *
	 *	\brief Generates code for "ParserDefinitionTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class ParserDefinitionTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			file_,
			first_production_rule_declaration_,
			language_name_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			nonterminal_declaration_,
			nonterminal_name_,
			production_id_,
			production_rule_,
			production_rule_declaration_,
			production_rule_id_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,
			second_production_rule_declaration_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char* ConvertEnumToName(
			::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Unknown: {
				return "Unknown";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope: {
				return "Scope";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::file_: {
				return "file";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				first_production_rule_declaration_: {
				return "first_production_rule_declaration";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				language_name_: {
				return "language_name";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				left_bracket_: {
				return "left_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				nonterminal_declaration_: {
				return "nonterminal_declaration";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				nonterminal_name_: {
				return "nonterminal_name";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				production_id_: {
				return "production_id";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				production_rule_: {
				return "production_rule";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				production_rule_declaration_: {
				return "production_rule_declaration";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				production_rule_id_: {
				return "production_rule_id";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				right_bracket_: {
				return "right_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				right_curly_bracket_: {
				return "right_curly_bracket";
			}

			case ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
				second_production_rule_declaration_: {
				return "second_production_rule_declaration";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type type =
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType scope_type =
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;
			}

			VariableScope(
				const char* text,
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;
			}

			VariableScope(
				std::vector<VariableBase*> variable,
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									ScopeType::Upper_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									ScopeType::Lower_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									ScopeType::Snake_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									ScopeType::Slash_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									ScopeType::DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(
				::deamer::templates::antlr::parser::ParserDefinitionTemplate::ScopeType::Default_,
				true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ =
				new VariableScope(::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									  ScopeType::Variable_Field_,
								  true);
			VariableBase* variable_field_separator_ =
				new VariableScope("\n",
								  ::deamer::templates::antlr::parser::ParserDefinitionTemplate::
									  ScopeType::Variable_Field_Separator_,
								  true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(ParserDefinitionTemplate* parserdefinitiontemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("parser grammar "),
					 GenerateVariable(parserdefinitiontemplate_->language_name_->This()),
					 GenerateVariable("Parser;\noptions\n"), GenerateVariable("{"),
					 GenerateVariable("\n\ttokenVocab = "),
					 GenerateVariable(parserdefinitiontemplate_->language_name_->This()),
					 GenerateVariable("Lexer;\n"), GenerateVariable("}"), GenerateVariable("\n\n"),
					 GenerateVariable(
						 parserdefinitiontemplate_->nonterminal_declaration_->Variable_Field())}));
				Content_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) = VariableBase(
					std::vector<VariableBase*>({GenerateVariable("ParserDefinition")}));
				File_name_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("deamer::templates::antlr::parser")}));
				Namespace_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type =
					::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_first_production_rule_declaration_ : public VariableScopes
		{
			static constexpr auto name = "first_production_rule_declaration_";

			Variable_first_production_rule_declaration_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					first_production_rule_declaration_;
			}

			virtual ~Variable_first_production_rule_declaration_() override = default;

			Variable_first_production_rule_declaration_(
				ParserDefinitionTemplate* parserdefinitiontemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					first_production_rule_declaration_;
			}

			Variable_first_production_rule_declaration_&
			operator=(const Variable_first_production_rule_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_name_ : public VariableScopes
		{
			static constexpr auto name = "language_name_";

			Variable_language_name_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					language_name_;
			}

			virtual ~Variable_language_name_() override = default;

			Variable_language_name_(ParserDefinitionTemplate* parserdefinitiontemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					language_name_;
			}

			Variable_language_name_& operator=(const Variable_language_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_declaration_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_declaration_";

			Variable_nonterminal_declaration_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					nonterminal_declaration_;
			}

			virtual ~Variable_nonterminal_declaration_() override = default;

			Variable_nonterminal_declaration_(ParserDefinitionTemplate* parserdefinitiontemplate_,
											  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					nonterminal_declaration_;
			}

			Variable_nonterminal_declaration_&
			operator=(const Variable_nonterminal_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_name_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_name_";

			Variable_nonterminal_name_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					nonterminal_name_;
			}

			virtual ~Variable_nonterminal_name_() override = default;

			Variable_nonterminal_name_(ParserDefinitionTemplate* parserdefinitiontemplate_,
									   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					nonterminal_name_;
			}

			Variable_nonterminal_name_& operator=(const Variable_nonterminal_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_id_ : public VariableScopes
		{
			static constexpr auto name = "production_id_";

			Variable_production_id_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_id_;
			}

			virtual ~Variable_production_id_() override = default;

			Variable_production_id_(ParserDefinitionTemplate* parserdefinitiontemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_id_;
			}

			Variable_production_id_& operator=(const Variable_production_id_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_";

			Variable_production_rule_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_;
			}

			virtual ~Variable_production_rule_() override = default;

			Variable_production_rule_(ParserDefinitionTemplate* parserdefinitiontemplate_,
									  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_;
			}

			Variable_production_rule_& operator=(const Variable_production_rule_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_declaration_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_declaration_";

			Variable_production_rule_declaration_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_declaration_;
			}

			virtual ~Variable_production_rule_declaration_() override = default;

			Variable_production_rule_declaration_(
				ParserDefinitionTemplate* parserdefinitiontemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_declaration_;
			}

			Variable_production_rule_declaration_&
			operator=(const Variable_production_rule_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_id_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_id_";

			Variable_production_rule_id_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_id_;
			}

			virtual ~Variable_production_rule_id_() override = default;

			Variable_production_rule_id_(ParserDefinitionTemplate* parserdefinitiontemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					production_rule_id_;
			}

			Variable_production_rule_id_& operator=(const Variable_production_rule_id_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(ParserDefinitionTemplate* parserdefinitiontemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_second_production_rule_declaration_ : public VariableScopes
		{
			static constexpr auto name = "second_production_rule_declaration_";

			Variable_second_production_rule_declaration_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					second_production_rule_declaration_;
			}

			virtual ~Variable_second_production_rule_declaration_() override = default;

			Variable_second_production_rule_declaration_(
				ParserDefinitionTemplate* parserdefinitiontemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::ParserDefinitionTemplate::Type::
					second_production_rule_declaration_;
			}

			Variable_second_production_rule_declaration_&
			operator=(const Variable_second_production_rule_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. ParserDefinitionTemplate.member = "auto-generated";
		Variable_file_* file_ = new Variable_file_();
		Variable_first_production_rule_declaration_* first_production_rule_declaration_ =
			new Variable_first_production_rule_declaration_();
		Variable_language_name_* language_name_ = new Variable_language_name_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_nonterminal_declaration_* nonterminal_declaration_ =
			new Variable_nonterminal_declaration_();
		Variable_nonterminal_name_* nonterminal_name_ = new Variable_nonterminal_name_();
		Variable_production_id_* production_id_ = new Variable_production_id_();
		Variable_production_rule_* production_rule_ = new Variable_production_rule_();
		Variable_production_rule_declaration_* production_rule_declaration_ =
			new Variable_production_rule_declaration_();
		Variable_production_rule_id_* production_rule_id_ = new Variable_production_rule_id_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();
		Variable_second_production_rule_declaration_* second_production_rule_declaration_ =
			new Variable_second_production_rule_declaration_();

	public:
		ParserDefinitionTemplate()
		{
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*first_production_rule_declaration_ = Variable_first_production_rule_declaration_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("\t"), GenerateVariable(production_rule_->This()),
						   GenerateVariable(" "), GenerateVariable(production_rule_id_->This())}));
			*language_name_ = Variable_language_name_(this, std::vector<VariableBase*>({}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*nonterminal_declaration_ = Variable_nonterminal_declaration_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("\n"), GenerateVariable(nonterminal_name_->This()),
						   GenerateVariable(":\n"),
						   GenerateVariable(production_rule_declaration_->Variable_Field()),
						   GenerateVariable("\n\t;")}));
			*nonterminal_name_ = Variable_nonterminal_name_(this, std::vector<VariableBase*>({}));
			*production_id_ = Variable_production_id_(this, std::vector<VariableBase*>({}));
			*production_rule_ = Variable_production_rule_(this, std::vector<VariableBase*>({}));
			*production_rule_declaration_ =
				Variable_production_rule_declaration_(this, std::vector<VariableBase*>({}));
			*production_rule_id_ = Variable_production_rule_id_(
				this, std::vector<VariableBase*>({GenerateVariable("# productionrule_"),
												  GenerateVariable(nonterminal_name_->This()),
												  GenerateVariable("_"),
												  GenerateVariable(production_id_->This())}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));
			*second_production_rule_declaration_ = Variable_second_production_rule_declaration_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("\t| "), GenerateVariable(production_rule_->This()),
						   GenerateVariable(" "), GenerateVariable(production_rule_id_->This())}));

			variables_.emplace_back(file_);
			variables_.emplace_back(first_production_rule_declaration_);
			variables_.emplace_back(language_name_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(nonterminal_declaration_);
			variables_.emplace_back(nonterminal_name_);
			variables_.emplace_back(production_id_);
			variables_.emplace_back(production_rule_);
			variables_.emplace_back(production_rule_declaration_);
			variables_.emplace_back(production_rule_id_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
			variables_.emplace_back(second_production_rule_declaration_);
		}

		virtual ~ParserDefinitionTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_ANTLR_PARSER_PARSERDEFINITIONTEMPLATE_h
