#ifndef DEAMER_TEMPLATES_AST_TYPE_CPP_GRAPHTEMPLATE_h
#define DEAMER_TEMPLATES_AST_TYPE_CPP_GRAPHTEMPLATE_h

#include <variant>
#include <vector>
#include <string>

namespace deamer::templates::ast::type::cpp
{

	/*!	\class GraphTemplate
	 *
	 *	\brief Generates code for "GraphTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class GraphTemplate
	{
	public:
		enum class Type
{
Unknown,
Scope,

// User defined types
class_name_,
const_qualifier_,
file_,
header_guard_,
language_name_,
language_name_underscore_,
left_angle_bracket_,
left_bracket_,
left_curly_bracket_,
listen_object_entry_,
listen_object_exit_,
object_,
right_angle_bracket_,
right_bracket_,
right_curly_bracket_,


};


		enum class ScopeType
{
Unknown,

// Default
Default_,
Upper_,
Lower_,

Snake_,
Slash_,
BackSlash_,
Colon_,
DoubleColon_,

Variable_Field_,
Variable_Field_Separator_,
Function_Field_,
Function_Field_Separator_,


};


		static constexpr const char* ConvertEnumToName(::deamer::templates::ast::type::cpp::GraphTemplate::Type enumerationValue)
{
	switch(enumerationValue)
	{
	case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::class_name_:
{
	return "class_name";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::const_qualifier_:
{
	return "const_qualifier";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::file_:
{
	return "file";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::header_guard_:
{
	return "header_guard";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_:
{
	return "language_name";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_underscore_:
{
	return "language_name_underscore";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_angle_bracket_:
{
	return "left_angle_bracket";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_bracket_:
{
	return "left_bracket";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_curly_bracket_:
{
	return "left_curly_bracket";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_entry_:
{
	return "listen_object_entry";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_exit_:
{
	return "listen_object_exit";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::object_:
{
	return "object";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_angle_bracket_:
{
	return "right_angle_bracket";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_bracket_:
{
	return "right_bracket";
}

case ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_curly_bracket_:
{
	return "right_curly_bracket";
}


	}

	return "";
}


		
	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::ast::type::cpp::GraphTemplate::Type type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({ currentValueAsVariableBase, variable });

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		
		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType scope_type = ::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;
			}

			VariableScope(const char* text, ::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(text), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable, ::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(variable), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;
			}
		};
		
		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
			: VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Upper_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};
		
		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
			: VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Lower_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};
		
		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
			: VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Snake_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};
		
		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
			: VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Slash_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};
		
		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
			: VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::DoubleColon_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Default_, true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);
			
			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);
			
			VariableBase* variable_field_ = new VariableScope(::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Variable_Field_, true);
			VariableBase* variable_field_separator_ = new VariableScope("\n", ::deamer::templates::ast::type::cpp::GraphTemplate::ScopeType::Variable_Field_Separator_, true);

			// Ctor
			VariableScopes() : VariableBase() {}

			VariableScopes(const char* text) : VariableBase(text) {}

			VariableScopes(const std::string& text) : VariableBase(text) {}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables) {}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		
struct Variable_class_name_ : public VariableScopes
{

static constexpr auto name = "class_name_";



Variable_class_name_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::class_name_;
}

virtual ~Variable_class_name_() override = default;

Variable_class_name_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::class_name_;

}



Variable_class_name_& operator=(const Variable_class_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_const_qualifier_ : public VariableScopes
{

static constexpr auto name = "const_qualifier_";



Variable_const_qualifier_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::const_qualifier_;
}

virtual ~Variable_const_qualifier_() override = default;

Variable_const_qualifier_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::const_qualifier_;

}



Variable_const_qualifier_& operator=(const Variable_const_qualifier_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_file_ : public VariableScopes
{

static constexpr auto name = "file_";

VariableBase* Content_ = GenerateVariable("");
VariableBase* Class_postfix_ = GenerateVariable("");
VariableBase* Extension_ = GenerateVariable("");
VariableBase* File_name_ = GenerateVariable("");
VariableBase* Namespace_ = GenerateVariable("");
VariableBase* Target_language_ = GenerateVariable("");


Variable_file_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::file_;
}

virtual ~Variable_file_() override = default;

Variable_file_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::file_;
*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("#ifndef "), GenerateVariable(graphtemplate_->header_guard_->This()), GenerateVariable("\n#define "), GenerateVariable(graphtemplate_->header_guard_->This()), GenerateVariable("\n\n#include \""), GenerateVariable(graphtemplate_->language_name_->This()), GenerateVariable("/Ast/Listener/EnterExitListener"), GenerateVariable("."), GenerateVariable("h\"\n\nnamespace "), GenerateVariable(graphtemplate_->language_name_->This()), GenerateVariable(" "), GenerateVariable("{"), GenerateVariable(" namespace ast "), GenerateVariable("{"), GenerateVariable(" namespace listener "), GenerateVariable("{"), GenerateVariable(" namespace deamer "), GenerateVariable("{"), GenerateVariable(" namespace visualisation "), GenerateVariable("{"), GenerateVariable("\n\n\tclass Graph : public EnterExitListener\n\t"), GenerateVariable("{"), GenerateVariable("\n\tprivate:\n\t\tstd::string output;\n\n\t\tvoid Init()\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\toutput += \"digraph "), GenerateVariable(graphtemplate_->language_name_->This()), GenerateVariable("_AST "), GenerateVariable("{"), GenerateVariable("\\"), GenerateVariable("n\";\n\t\t"), GenerateVariable("}"), GenerateVariable("\n\n\t\tvoid End()\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\toutput += \""), GenerateVariable("}"), GenerateVariable("\\"), GenerateVariable("n\";\n\t\t"), GenerateVariable("}"), GenerateVariable("\n\n\t\tvoid AddConnection("), GenerateVariable(graphtemplate_->const_qualifier_->This()), GenerateVariable("  ::deamer::external::cpp::ast::Node* source, "), GenerateVariable(graphtemplate_->const_qualifier_->This()), GenerateVariable("  ::deamer::external::cpp::ast::Node* target)\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\toutput += \""), GenerateVariable("\\"), GenerateVariable("t\" + std::to_string(::std::size_t(source)) + \" -> \" + std::to_string(::std::size_t(target)) + \";"), GenerateVariable("\\"), GenerateVariable("n\";\n\t\t"), GenerateVariable("}"), GenerateVariable("\n\n\t\t"), GenerateVariable(graphtemplate_->listen_object_entry_->Variable_Field()), GenerateVariable("\n\t\t"), GenerateVariable(graphtemplate_->listen_object_exit_->Variable_Field()), GenerateVariable("\n\n\tpublic:\n\t\tGraph()\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\tInit();\n\t\t"), GenerateVariable("}"), GenerateVariable("\n\n\n\t\tstd::string GetGraph()\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\tEnd();\n\t\t\treturn output;\n\t\t"), GenerateVariable("}"), GenerateVariable("\n\t"), GenerateVariable("}"), GenerateVariable(";\n\n"), GenerateVariable("}}"), GenerateVariable("}}"), GenerateVariable("}"), GenerateVariable("\n\n#endif // "), GenerateVariable(graphtemplate_->header_guard_->This()) }));
Content_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;

*static_cast<VariableBase*>(Class_postfix_) = VariableBase(std::vector<VariableBase*>({  }));
Class_postfix_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;

*static_cast<VariableBase*>(Extension_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("h") }));
Extension_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;

*static_cast<VariableBase*>(File_name_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable(graphtemplate_->class_name_->This()) }));
File_name_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;

*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("deamer::templates::ast::type::cpp") }));
Namespace_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;

*static_cast<VariableBase*>(Target_language_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("C++") }));
Target_language_->type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::Scope;


}


VariableBase* Content() const
{
	return Content_;
}

VariableBase* Class_postfix() const
{
	return Class_postfix_;
}

VariableBase* Extension() const
{
	return Extension_;
}

VariableBase* File_name() const
{
	return File_name_;
}

VariableBase* Namespace() const
{
	return Namespace_;
}

VariableBase* Target_language() const
{
	return Target_language_;
}


Variable_file_& operator=(const Variable_file_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	*Content_ = *variable.Content_;
*Class_postfix_ = *variable.Class_postfix_;
*Extension_ = *variable.Extension_;
*File_name_ = *variable.File_name_;
*Namespace_ = *variable.Namespace_;
*Target_language_ = *variable.Target_language_;


	return *this;
}

};

struct Variable_header_guard_ : public VariableScopes
{

static constexpr auto name = "header_guard_";



Variable_header_guard_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::header_guard_;
}

virtual ~Variable_header_guard_() override = default;

Variable_header_guard_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::header_guard_;

}



Variable_header_guard_& operator=(const Variable_header_guard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_language_name_ : public VariableScopes
{

static constexpr auto name = "language_name_";



Variable_language_name_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_;
}

virtual ~Variable_language_name_() override = default;

Variable_language_name_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_;

}



Variable_language_name_& operator=(const Variable_language_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_language_name_underscore_ : public VariableScopes
{

static constexpr auto name = "language_name_underscore_";



Variable_language_name_underscore_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_underscore_;
}

virtual ~Variable_language_name_underscore_() override = default;

Variable_language_name_underscore_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::language_name_underscore_;

}



Variable_language_name_underscore_& operator=(const Variable_language_name_underscore_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "left_angle_bracket_";



Variable_left_angle_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_angle_bracket_;
}

virtual ~Variable_left_angle_bracket_() override = default;

Variable_left_angle_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_angle_bracket_;

}



Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_bracket_ : public VariableScopes
{

static constexpr auto name = "left_bracket_";



Variable_left_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_bracket_;
}

virtual ~Variable_left_bracket_() override = default;

Variable_left_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_bracket_;

}



Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "left_curly_bracket_";



Variable_left_curly_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_curly_bracket_;
}

virtual ~Variable_left_curly_bracket_() override = default;

Variable_left_curly_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::left_curly_bracket_;

}



Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_listen_object_entry_ : public VariableScopes
{

static constexpr auto name = "listen_object_entry_";



Variable_listen_object_entry_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_entry_;
}

virtual ~Variable_listen_object_entry_() override = default;

Variable_listen_object_entry_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_entry_;

}



Variable_listen_object_entry_& operator=(const Variable_listen_object_entry_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_listen_object_exit_ : public VariableScopes
{

static constexpr auto name = "listen_object_exit_";



Variable_listen_object_exit_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_exit_;
}

virtual ~Variable_listen_object_exit_() override = default;

Variable_listen_object_exit_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::listen_object_exit_;

}



Variable_listen_object_exit_& operator=(const Variable_listen_object_exit_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_object_ : public VariableScopes
{

static constexpr auto name = "object_";



Variable_object_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::object_;
}

virtual ~Variable_object_() override = default;

Variable_object_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::object_;

}



Variable_object_& operator=(const Variable_object_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "right_angle_bracket_";



Variable_right_angle_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_angle_bracket_;
}

virtual ~Variable_right_angle_bracket_() override = default;

Variable_right_angle_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_angle_bracket_;

}



Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_bracket_ : public VariableScopes
{

static constexpr auto name = "right_bracket_";



Variable_right_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_bracket_;
}

virtual ~Variable_right_bracket_() override = default;

Variable_right_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_bracket_;

}



Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "right_curly_bracket_";



Variable_right_curly_bracket_() : VariableScopes()
{
	type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_curly_bracket_;
}

virtual ~Variable_right_curly_bracket_() override = default;

Variable_right_curly_bracket_(GraphTemplate* graphtemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::deamer::templates::ast::type::cpp::GraphTemplate::Type::right_curly_bracket_;

}



Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};


	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. GraphTemplate.member = "auto-generated";
		Variable_class_name_* class_name_ = new Variable_class_name_();
Variable_const_qualifier_* const_qualifier_ = new Variable_const_qualifier_();
Variable_file_* file_ = new Variable_file_();
Variable_header_guard_* header_guard_ = new Variable_header_guard_();
Variable_language_name_* language_name_ = new Variable_language_name_();
Variable_language_name_underscore_* language_name_underscore_ = new Variable_language_name_underscore_();
Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
Variable_listen_object_entry_* listen_object_entry_ = new Variable_listen_object_entry_();
Variable_listen_object_exit_* listen_object_exit_ = new Variable_listen_object_exit_();
Variable_object_* object_ = new Variable_object_();
Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();


	public:
		GraphTemplate()
		{
			*class_name_ = Variable_class_name_(this, std::vector<VariableBase*>({ GenerateVariable("Graph") }));
*const_qualifier_ = Variable_const_qualifier_(this, std::vector<VariableBase*>({ GenerateVariable("const") }));
*file_ = Variable_file_(this, std::vector<VariableBase*>({  }));
*header_guard_ = Variable_header_guard_(this, std::vector<VariableBase*>({ GenerateVariable(language_name_underscore_->Upper()), GenerateVariable("_AST_VISUALISATION_"), GenerateVariable(class_name_->Upper()), GenerateVariable("_H") }));
*language_name_ = Variable_language_name_(this, std::vector<VariableBase*>({  }));
*language_name_underscore_ = Variable_language_name_underscore_(this, std::vector<VariableBase*>({ GenerateVariable(language_name_->Underscore()) }));
*left_angle_bracket_ = Variable_left_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("<") }));
*left_bracket_ = Variable_left_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("{") }));
*left_curly_bracket_ = Variable_left_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("(") }));
*listen_object_entry_ = Variable_listen_object_entry_(this, std::vector<VariableBase*>({ GenerateVariable("\n\t\tvoid ListenEntry("), GenerateVariable(const_qualifier_->This()), GenerateVariable(" ::"), GenerateVariable(language_name_->This()), GenerateVariable("::ast::node::"), GenerateVariable(object_->This()), GenerateVariable("* node) override\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\tfor ("), GenerateVariable(const_qualifier_->This()), GenerateVariable(" auto* child : node-"), GenerateVariable(right_angle_bracket_->This()), GenerateVariable("GetNodes())\n\t\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t\t\tAddConnection(node, child);\n\t\t\t"), GenerateVariable("}"), GenerateVariable("\n\n\t\t\toutput += \""), GenerateVariable("\\"), GenerateVariable("t\" + std::to_string(::std::size_t(node)) + \" [label="), GenerateVariable("\\"), GenerateVariable("\""), GenerateVariable(object_->This()), GenerateVariable("\\"), GenerateVariable("\"];"), GenerateVariable("\\"), GenerateVariable("n\";\n\t\t"), GenerateVariable("}") }));
*listen_object_exit_ = Variable_listen_object_exit_(this, std::vector<VariableBase*>({ GenerateVariable("\n\t\tvoid ListenExit("), GenerateVariable(const_qualifier_->This()), GenerateVariable(" ::"), GenerateVariable(language_name_->This()), GenerateVariable("::ast::node::"), GenerateVariable(object_->This()), GenerateVariable("* node) override\n\t\t"), GenerateVariable("{"), GenerateVariable("\n\t\t"), GenerateVariable("}") }));
*object_ = Variable_object_(this, std::vector<VariableBase*>({  }));
*right_angle_bracket_ = Variable_right_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(">") }));
*right_bracket_ = Variable_right_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("}") }));
*right_curly_bracket_ = Variable_right_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(")") }));


			variables_.emplace_back(class_name_);
variables_.emplace_back(const_qualifier_);
variables_.emplace_back(file_);
variables_.emplace_back(header_guard_);
variables_.emplace_back(language_name_);
variables_.emplace_back(language_name_underscore_);
variables_.emplace_back(left_angle_bracket_);
variables_.emplace_back(left_bracket_);
variables_.emplace_back(left_curly_bracket_);
variables_.emplace_back(listen_object_entry_);
variables_.emplace_back(listen_object_exit_);
variables_.emplace_back(object_);
variables_.emplace_back(right_angle_bracket_);
variables_.emplace_back(right_bracket_);
variables_.emplace_back(right_curly_bracket_);

		}

		virtual ~GraphTemplate()
		{
			for(auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_AST_TYPE_CPP_GRAPHTEMPLATE_h
