#ifndef DEAMER_TEMPLATES_ANTLR_PARSER_FINDANTLRTEMPLATE_h
#define DEAMER_TEMPLATES_ANTLR_PARSER_FINDANTLRTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace deamer::templates::antlr::parser
{
	/*!	\class FindAntlrTemplate
	 *
	 *	\brief Generates code for "FindAntlrTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class FindAntlrTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			file_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char* ConvertEnumToName(
			::deamer::templates::antlr::parser::FindAntlrTemplate::Type enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Unknown: {
				return "Unknown";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope: {
				return "Scope";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::file_: {
				return "file";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::left_bracket_: {
				return "left_bracket";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
				right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::right_bracket_: {
				return "right_bracket";
			}

			case ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
				right_curly_bracket_: {
				return "right_curly_bracket";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::antlr::parser::FindAntlrTemplate::Type type =
				::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType scope_type =
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;
			}

			VariableScope(
				const char* text,
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;
			}

			VariableScope(
				std::vector<VariableBase*> variable,
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType scope_type_,
				bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(
					  ::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Upper_,
					  true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(
					  ::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Lower_,
					  true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(
					  ::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Snake_,
					  true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(
					  ::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Slash_,
					  true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::
									DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Default_, true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ = new VariableScope(
				::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::Variable_Field_,
				true);
			VariableBase* variable_field_separator_ =
				new VariableScope("\n",
								  ::deamer::templates::antlr::parser::FindAntlrTemplate::ScopeType::
									  Variable_Field_Separator_,
								  true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(FindAntlrTemplate* findantlrtemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("find_package(Java QUIET COMPONENTS Runtime)\n\nif(NOT "
									  "ANTLR_EXECUTABLE)\n  find_program(ANTLR_EXECUTABLE\n        "
									  "       NAMES antlr"),
					 GenerateVariable("."),
					 GenerateVariable("jar antlr4"),
					 GenerateVariable("."),
					 GenerateVariable("jar antlr-4"),
					 GenerateVariable("."),
					 GenerateVariable("jar antlr-4"),
					 GenerateVariable("."),
					 GenerateVariable("11"),
					 GenerateVariable("."),
					 GenerateVariable("1-complete"),
					 GenerateVariable("."),
					 GenerateVariable("jar)\nendif()\n\nif(ANTLR_EXECUTABLE AND "
									  "Java_JAVA_EXECUTABLE)\n  execute_process(\n      COMMAND $"),
					 GenerateVariable("{"),
					 GenerateVariable("Java_JAVA_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable(" -jar $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 "\n      OUTPUT_VARIABLE ANTLR_COMMAND_OUTPUT\n      ERROR_VARIABLE "
						 "ANTLR_COMMAND_ERROR\n      RESULT_VARIABLE ANTLR_COMMAND_RESULT\n      "
						 "OUTPUT_STRIP_TRAILING_WHITESPACE)\n\n  if(ANTLR_COMMAND_RESULT EQUAL "
						 "0)\n    string(REGEX MATCH \"Version [0-9]+("),
					 GenerateVariable("\\"),
					 GenerateVariable("\\"),
					 GenerateVariable("."),
					 GenerateVariable("[0-9]+)*\" ANTLR_VERSION $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_COMMAND_OUTPUT"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n    string(REPLACE \"Version \" \"\" ANTLR_VERSION $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_VERSION"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 ")\n  else()\n    message(\n        SEND_ERROR\n        \"Command '$"),
					 GenerateVariable("{"),
					 GenerateVariable("Java_JAVA_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable(" -jar $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable("' \"\n        \"failed with the output '$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_COMMAND_ERROR"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 "'\")\n  endif()\n\n  macro(ANTLR_TARGET Name InputFile)\n    "
						 "set(ANTLR_OPTIONS LEXER PARSER LISTENER VISITOR)\n    "
						 "set(ANTLR_ONE_VALUE_ARGS PACKAGE OUTPUT_DIRECTORY DEPENDS_ANTLR)\n    "
						 "set(ANTLR_MULTI_VALUE_ARGS COMPILE_FLAGS DEPENDS)\n    "
						 "cmake_parse_arguments(ANTLR_TARGET\n                          \"$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_OPTIONS"),
					 GenerateVariable("}"),
					 GenerateVariable("\"\n                          \"$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_ONE_VALUE_ARGS"),
					 GenerateVariable("}"),
					 GenerateVariable("\"\n                          \"$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_MULTI_VALUE_ARGS"),
					 GenerateVariable("}"),
					 GenerateVariable("\"\n                          $"),
					 GenerateVariable("{"),
					 GenerateVariable("ARGN"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n\n    set(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_INPUT $"),
					 GenerateVariable("{"),
					 GenerateVariable("InputFile"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n\n    get_filename_component(ANTLR_INPUT $"),
					 GenerateVariable("{"),
					 GenerateVariable("InputFile"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 " NAME_WE)\n\n    if(ANTLR_TARGET_OUTPUT_DIRECTORY)\n      set(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_OUTPUT_DIRECTORY"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n    else()\n      set(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR\n          $"),
					 GenerateVariable("{"),
					 GenerateVariable("CMAKE_CURRENT_BINARY_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/antlr4cpp_generated_src/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n    endif()\n\n    unset(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS)\n\n    if((ANTLR_TARGET_LEXER AND NOT "
									  "ANTLR_TARGET_PARSER) OR\n       (ANTLR_TARGET_PARSER AND "
									  "NOT ANTLR_TARGET_LEXER))\n      list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("."),
					 GenerateVariable("cpp)\n      set(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUTS\n          $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("."),
					 GenerateVariable("interp\n          $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("."),
					 GenerateVariable("tokens)\n    else()\n      list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Lexer"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Lexer"),
					 GenerateVariable("."),
					 GenerateVariable("cpp\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Parser"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Parser"),
					 GenerateVariable("."),
					 GenerateVariable("cpp)\n      list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUTS\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Lexer"),
					 GenerateVariable("."),
					 GenerateVariable("interp\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Lexer"),
					 GenerateVariable("."),
					 GenerateVariable("tokens)\n    endif()\n\n    if(ANTLR_TARGET_LISTENER)\n     "
									  " list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("BaseListener"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("BaseListener"),
					 GenerateVariable("."),
					 GenerateVariable("cpp\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Listener"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Listener"),
					 GenerateVariable("."),
					 GenerateVariable(
						 "cpp)\n      list(APPEND ANTLR_TARGET_COMPILE_FLAGS -listener)\n    "
						 "endif()\n\n    if(ANTLR_TARGET_VISITOR)\n      list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("BaseVisitor"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("BaseVisitor"),
					 GenerateVariable("."),
					 GenerateVariable("cpp\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Visitor"),
					 GenerateVariable("."),
					 GenerateVariable("h\n           $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable("Visitor"),
					 GenerateVariable("."),
					 GenerateVariable("cpp)\n      list(APPEND ANTLR_TARGET_COMPILE_FLAGS "
									  "-visitor)\n    endif()\n\n    if(ANTLR_TARGET_PACKAGE)\n    "
									  "  list(APPEND ANTLR_TARGET_COMPILE_FLAGS -package $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_PACKAGE"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n    endif()\n\n    list(APPEND ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUTS $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_CXX_OUTPUTS"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n\n    if(ANTLR_TARGET_DEPENDS_ANTLR)\n      if(ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_DEPENDS_ANTLR"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 "_INPUT)\n        list(APPEND ANTLR_TARGET_DEPENDS\n             $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_DEPENDS_ANTLR"),
					 GenerateVariable("}"),
					 GenerateVariable("_INPUT"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 ")\n        list(APPEND ANTLR_TARGET_DEPENDS\n             $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_DEPENDS_ANTLR"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUTS"),
					 GenerateVariable("}"),
					 GenerateVariable(")\n      else()\n        message(SEND_ERROR\n               "
									  " \"ANTLR target '$"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_DEPENDS_ANTLR"),
					 GenerateVariable("}"),
					 GenerateVariable("' not found\")\n      endif()\n    endif()\n\n    "
									  "add_custom_command(\n        OUTPUT $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUTS"),
					 GenerateVariable("}"),
					 GenerateVariable("\n        COMMAND $"),
					 GenerateVariable("{"),
					 GenerateVariable("Java_JAVA_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable(" -jar $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_EXECUTABLE"),
					 GenerateVariable("}"),
					 GenerateVariable("\n                $"),
					 GenerateVariable("{"),
					 GenerateVariable("InputFile"),
					 GenerateVariable("}"),
					 GenerateVariable("\n                -o $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_$"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable("_OUTPUT_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("\n                -no-listener\n                "
									  "-Dlanguage=Cpp\n                $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_COMPILE_FLAGS"),
					 GenerateVariable("}"),
					 GenerateVariable("\n        DEPENDS $"),
					 GenerateVariable("{"),
					 GenerateVariable("InputFile"),
					 GenerateVariable("}"),
					 GenerateVariable("\n                $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_TARGET_DEPENDS"),
					 GenerateVariable("}"),
					 GenerateVariable("\n        WORKING_DIRECTORY $"),
					 GenerateVariable("{"),
					 GenerateVariable("CMAKE_CURRENT_SOURCE_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("\n        COMMENT \"Building $"),
					 GenerateVariable("{"),
					 GenerateVariable("Name"),
					 GenerateVariable("}"),
					 GenerateVariable(" with ANTLR $"),
					 GenerateVariable("{"),
					 GenerateVariable("ANTLR_VERSION"),
					 GenerateVariable("}"),
					 GenerateVariable(
						 "\")\n  endmacro(ANTLR_TARGET)\n\nendif(ANTLR_EXECUTABLE AND "
						 "Java_JAVA_EXECUTABLE)\n\ninclude(FindPackageHandleStandardArgs)\nfind_"
						 "package_handle_standard_args(\n    ANTLR\n    REQUIRED_VARS "
						 "ANTLR_EXECUTABLE Java_JAVA_EXECUTABLE\n    VERSION_VAR "
						 "ANTLR_VERSION)\n")}));
				Content_->type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type =
					::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type =
					::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("FindAntlr")}));
				File_name_->type =
					::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("deamer::templates::antlr::parser")}));
				Namespace_->type =
					::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type =
					::deamer::templates::antlr::parser::FindAntlrTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(FindAntlrTemplate* findantlrtemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(FindAntlrTemplate* findantlrtemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(FindAntlrTemplate* findantlrtemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(FindAntlrTemplate* findantlrtemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(FindAntlrTemplate* findantlrtemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(FindAntlrTemplate* findantlrtemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::antlr::parser::FindAntlrTemplate::Type::
					right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. FindAntlrTemplate.member = "auto-generated";
		Variable_file_* file_ = new Variable_file_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();

	public:
		FindAntlrTemplate()
		{
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));

			variables_.emplace_back(file_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
		}

		virtual ~FindAntlrTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_ANTLR_PARSER_FINDANTLRTEMPLATE_h
