#ifndef DEAMER_TEMPLATES_DEAMERDOCUMENTATION_GRAMMAR_MARKDOWN_NONTERMINALTEMPLATE_h
#define DEAMER_TEMPLATES_DEAMERDOCUMENTATION_GRAMMAR_MARKDOWN_NONTERMINALTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace deamer::templates::deamerdocumentation::grammar::markdown
{
	/*!	\class NonTerminalTemplate
	 *
	 *	\brief Generates code for "NonTerminalTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class NonTerminalTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			abstraction_,
			file_,
			inlined_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			nonterminal_name_,
			nonterminal_production_rule_,
			nonterminal_reference_,
			nonterminal_reference_section_,
			optional_nonterminal_reference_section_,
			production_rule_,
			production_rule_empty_member_,
			production_rule_member_,
			production_rule_member_name_,
			production_rule_nonterminal_member_,
			production_rule_terminal_member_,
			referencing_nonterminal_name_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,
			this_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char* ConvertEnumToName(
			::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::Type
				enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::abstraction_: {
				return "abstraction";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::file_: {
				return "file";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::inlined_: {
				return "inlined";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::left_bracket_: {
				return "left_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::nonterminal_name_: {
				return "nonterminal_name";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::nonterminal_production_rule_: {
				return "nonterminal_production_rule";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::nonterminal_reference_: {
				return "nonterminal_reference";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::nonterminal_reference_section_: {
				return "nonterminal_reference_section";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::optional_nonterminal_reference_section_: {
				return "optional_nonterminal_reference_section";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_: {
				return "production_rule";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_empty_member_: {
				return "production_rule_empty_member";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_member_: {
				return "production_rule_member";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_member_name_: {
				return "production_rule_member_name";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_nonterminal_member_: {
				return "production_rule_nonterminal_member";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::production_rule_terminal_member_: {
				return "production_rule_terminal_member";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::referencing_nonterminal_name_: {
				return "referencing_nonterminal_name";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::right_bracket_: {
				return "right_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::right_curly_bracket_: {
				return "right_curly_bracket";
			}

			case ::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				Type::this_: {
				return "this";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::Type
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::deamerdocumentation::grammar::markdown::NonTerminalTemplate::
				ScopeType scope_type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
							  NonTerminalTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;
			}

			VariableScope(const char* text,
						  ::deamer::templates::deamerdocumentation::grammar::markdown::
							  NonTerminalTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable,
						  ::deamer::templates::deamerdocumentation::grammar::markdown::
							  NonTerminalTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									NonTerminalTemplate::ScopeType::Upper_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									NonTerminalTemplate::ScopeType::Lower_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									NonTerminalTemplate::ScopeType::Snake_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									NonTerminalTemplate::ScopeType::Slash_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									NonTerminalTemplate::ScopeType::DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ =
				new VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									  NonTerminalTemplate::ScopeType::Default_,
								  true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ =
				new VariableScope(::deamer::templates::deamerdocumentation::grammar::markdown::
									  NonTerminalTemplate::ScopeType::Variable_Field_,
								  true);
			VariableBase* variable_field_separator_ =
				new VariableScope("\n",
								  ::deamer::templates::deamerdocumentation::grammar::markdown::
									  NonTerminalTemplate::ScopeType::Variable_Field_Separator_,
								  true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_abstraction_ : public VariableScopes
		{
			static constexpr auto name = "abstraction_";

			Variable_abstraction_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::abstraction_;
			}

			virtual ~Variable_abstraction_() override = default;

			Variable_abstraction_(NonTerminalTemplate* nonterminaltemplate_,
								  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::abstraction_;
			}

			Variable_abstraction_& operator=(const Variable_abstraction_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(NonTerminalTemplate* nonterminaltemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("# NonTerminal: "),
					 GenerateVariable(nonterminaltemplate_->this_->This()),
					 GenerateVariable("\n\nOverview of the nonterminal: "),
					 GenerateVariable(nonterminaltemplate_->this_->This()),
					 GenerateVariable(
						 "\n\n\n\n## This\n\n| Name:                | Abstraction:    | Is Inlined "
						 "|\n| -------------------- | --------------- | ---------- |\n| "),
					 GenerateVariable(nonterminaltemplate_->nonterminal_name_->This()),
					 GenerateVariable(" | "),
					 GenerateVariable(nonterminaltemplate_->abstraction_->This()),
					 GenerateVariable(" | "),
					 GenerateVariable(nonterminaltemplate_->inlined_->This()),
					 GenerateVariable(
						 " |\n\n\n\n## ProductionRules\n\n| ProductionRule |\n| ---- |\n"),
					 GenerateVariable(
						 nonterminaltemplate_->nonterminal_production_rule_->Variable_Field()),
					 GenerateVariable("\n\n\n\n## Who references this\n\n"),
					 GenerateVariable(
						 nonterminaltemplate_->optional_nonterminal_reference_section_->This()),
					 GenerateVariable("\n\n")}));
				Content_->type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("NonTerminal")}));
				File_name_->type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable(
						"deamer::templates::deamerdocumentation::grammar::markdown")}));
				Namespace_->type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type = ::deamer::templates::deamerdocumentation::grammar::
					markdown::NonTerminalTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_inlined_ : public VariableScopes
		{
			static constexpr auto name = "inlined_";

			Variable_inlined_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::inlined_;
			}

			virtual ~Variable_inlined_() override = default;

			Variable_inlined_(NonTerminalTemplate* nonterminaltemplate_,
							  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::inlined_;
			}

			Variable_inlined_& operator=(const Variable_inlined_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(NonTerminalTemplate* nonterminaltemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(NonTerminalTemplate* nonterminaltemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(NonTerminalTemplate* nonterminaltemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_name_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_name_";

			Variable_nonterminal_name_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_name_;
			}

			virtual ~Variable_nonterminal_name_() override = default;

			Variable_nonterminal_name_(NonTerminalTemplate* nonterminaltemplate_,
									   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_name_;
			}

			Variable_nonterminal_name_& operator=(const Variable_nonterminal_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_production_rule_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_production_rule_";

			Variable_nonterminal_production_rule_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_production_rule_;
			}

			virtual ~Variable_nonterminal_production_rule_() override = default;

			Variable_nonterminal_production_rule_(NonTerminalTemplate* nonterminaltemplate_,
												  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_production_rule_;
			}

			Variable_nonterminal_production_rule_&
			operator=(const Variable_nonterminal_production_rule_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_reference_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_reference_";

			Variable_nonterminal_reference_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_reference_;
			}

			virtual ~Variable_nonterminal_reference_() override = default;

			Variable_nonterminal_reference_(NonTerminalTemplate* nonterminaltemplate_,
											const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_reference_;
			}

			Variable_nonterminal_reference_&
			operator=(const Variable_nonterminal_reference_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_nonterminal_reference_section_ : public VariableScopes
		{
			static constexpr auto name = "nonterminal_reference_section_";

			Variable_nonterminal_reference_section_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_reference_section_;
			}

			virtual ~Variable_nonterminal_reference_section_() override = default;

			Variable_nonterminal_reference_section_(NonTerminalTemplate* nonterminaltemplate_,
													const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::nonterminal_reference_section_;
			}

			Variable_nonterminal_reference_section_&
			operator=(const Variable_nonterminal_reference_section_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_optional_nonterminal_reference_section_ : public VariableScopes
		{
			static constexpr auto name = "optional_nonterminal_reference_section_";

			Variable_optional_nonterminal_reference_section_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::optional_nonterminal_reference_section_;
			}

			virtual ~Variable_optional_nonterminal_reference_section_() override = default;

			Variable_optional_nonterminal_reference_section_(
				NonTerminalTemplate* nonterminaltemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::optional_nonterminal_reference_section_;
			}

			Variable_optional_nonterminal_reference_section_&
			operator=(const Variable_optional_nonterminal_reference_section_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_";

			Variable_production_rule_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_;
			}

			virtual ~Variable_production_rule_() override = default;

			Variable_production_rule_(NonTerminalTemplate* nonterminaltemplate_,
									  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_;
			}

			Variable_production_rule_& operator=(const Variable_production_rule_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_empty_member_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_empty_member_";

			Variable_production_rule_empty_member_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_empty_member_;
			}

			virtual ~Variable_production_rule_empty_member_() override = default;

			Variable_production_rule_empty_member_(NonTerminalTemplate* nonterminaltemplate_,
												   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_empty_member_;
			}

			Variable_production_rule_empty_member_&
			operator=(const Variable_production_rule_empty_member_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_member_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_member_";

			Variable_production_rule_member_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_member_;
			}

			virtual ~Variable_production_rule_member_() override = default;

			Variable_production_rule_member_(NonTerminalTemplate* nonterminaltemplate_,
											 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_member_;
			}

			Variable_production_rule_member_&
			operator=(const Variable_production_rule_member_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_member_name_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_member_name_";

			Variable_production_rule_member_name_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_member_name_;
			}

			virtual ~Variable_production_rule_member_name_() override = default;

			Variable_production_rule_member_name_(NonTerminalTemplate* nonterminaltemplate_,
												  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_member_name_;
			}

			Variable_production_rule_member_name_&
			operator=(const Variable_production_rule_member_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_nonterminal_member_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_nonterminal_member_";

			Variable_production_rule_nonterminal_member_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_nonterminal_member_;
			}

			virtual ~Variable_production_rule_nonterminal_member_() override = default;

			Variable_production_rule_nonterminal_member_(
				NonTerminalTemplate* nonterminaltemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_nonterminal_member_;
			}

			Variable_production_rule_nonterminal_member_&
			operator=(const Variable_production_rule_nonterminal_member_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_production_rule_terminal_member_ : public VariableScopes
		{
			static constexpr auto name = "production_rule_terminal_member_";

			Variable_production_rule_terminal_member_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_terminal_member_;
			}

			virtual ~Variable_production_rule_terminal_member_() override = default;

			Variable_production_rule_terminal_member_(NonTerminalTemplate* nonterminaltemplate_,
													  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::production_rule_terminal_member_;
			}

			Variable_production_rule_terminal_member_&
			operator=(const Variable_production_rule_terminal_member_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_referencing_nonterminal_name_ : public VariableScopes
		{
			static constexpr auto name = "referencing_nonterminal_name_";

			Variable_referencing_nonterminal_name_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::referencing_nonterminal_name_;
			}

			virtual ~Variable_referencing_nonterminal_name_() override = default;

			Variable_referencing_nonterminal_name_(NonTerminalTemplate* nonterminaltemplate_,
												   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::referencing_nonterminal_name_;
			}

			Variable_referencing_nonterminal_name_&
			operator=(const Variable_referencing_nonterminal_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(NonTerminalTemplate* nonterminaltemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(NonTerminalTemplate* nonterminaltemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(NonTerminalTemplate* nonterminaltemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_this_ : public VariableScopes
		{
			static constexpr auto name = "this_";

			Variable_this_() : VariableScopes()
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::this_;
			}

			virtual ~Variable_this_() override = default;

			Variable_this_(NonTerminalTemplate* nonterminaltemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::deamerdocumentation::grammar::markdown::
					NonTerminalTemplate::Type::this_;
			}

			Variable_this_& operator=(const Variable_this_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. NonTerminalTemplate.member = "auto-generated";
		Variable_abstraction_* abstraction_ = new Variable_abstraction_();
		Variable_file_* file_ = new Variable_file_();
		Variable_inlined_* inlined_ = new Variable_inlined_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_nonterminal_name_* nonterminal_name_ = new Variable_nonterminal_name_();
		Variable_nonterminal_production_rule_* nonterminal_production_rule_ =
			new Variable_nonterminal_production_rule_();
		Variable_nonterminal_reference_* nonterminal_reference_ =
			new Variable_nonterminal_reference_();
		Variable_nonterminal_reference_section_* nonterminal_reference_section_ =
			new Variable_nonterminal_reference_section_();
		Variable_optional_nonterminal_reference_section_* optional_nonterminal_reference_section_ =
			new Variable_optional_nonterminal_reference_section_();
		Variable_production_rule_* production_rule_ = new Variable_production_rule_();
		Variable_production_rule_empty_member_* production_rule_empty_member_ =
			new Variable_production_rule_empty_member_();
		Variable_production_rule_member_* production_rule_member_ =
			new Variable_production_rule_member_();
		Variable_production_rule_member_name_* production_rule_member_name_ =
			new Variable_production_rule_member_name_();
		Variable_production_rule_nonterminal_member_* production_rule_nonterminal_member_ =
			new Variable_production_rule_nonterminal_member_();
		Variable_production_rule_terminal_member_* production_rule_terminal_member_ =
			new Variable_production_rule_terminal_member_();
		Variable_referencing_nonterminal_name_* referencing_nonterminal_name_ =
			new Variable_referencing_nonterminal_name_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();
		Variable_this_* this_ = new Variable_this_();

	public:
		NonTerminalTemplate()
		{
			*abstraction_ = Variable_abstraction_(this, std::vector<VariableBase*>({}));
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*inlined_ = Variable_inlined_(this, std::vector<VariableBase*>({}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*nonterminal_name_ = Variable_nonterminal_name_(this, std::vector<VariableBase*>({}));
			*nonterminal_production_rule_ = Variable_nonterminal_production_rule_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("| "),
						   GenerateVariable(production_rule_member_->Variable_Field()),
						   GenerateVariable(" |")}));
			*nonterminal_reference_ = Variable_nonterminal_reference_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("\n#### ["),
					 GenerateVariable(referencing_nonterminal_name_->This()),
					 GenerateVariable("]("), GenerateVariable("."), GenerateVariable("/"),
					 GenerateVariable("."), GenerateVariable("."), GenerateVariable("/Grammar/"),
					 GenerateVariable(referencing_nonterminal_name_->This()), GenerateVariable("."),
					 GenerateVariable(
						 "md)\n\n| Productionrule referencing this                      |\n| "
						 "---------------------------------------------------- |\n"),
					 GenerateVariable(production_rule_->Variable_Field())}));
			*nonterminal_reference_section_ = Variable_nonterminal_reference_section_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("### NonTerminals\n\n"),
						   GenerateVariable(nonterminal_reference_->Variable_Field())}));
			*optional_nonterminal_reference_section_ =
				Variable_optional_nonterminal_reference_section_(
					this, std::vector<VariableBase*>(
							  {GenerateVariable(nonterminal_reference_section_->This())}));
			*production_rule_ = Variable_production_rule_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("| "),
						   GenerateVariable(production_rule_member_->Variable_Field()),
						   GenerateVariable(" |")}));
			*production_rule_empty_member_ = Variable_production_rule_empty_member_(
				this, std::vector<VariableBase*>({GenerateVariable("EMPTY")}));
			*production_rule_member_ =
				Variable_production_rule_member_(this, std::vector<VariableBase*>({}));
			*production_rule_member_name_ =
				Variable_production_rule_member_name_(this, std::vector<VariableBase*>({}));
			*production_rule_nonterminal_member_ = Variable_production_rule_nonterminal_member_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("["), GenerateVariable(production_rule_member_name_->This()),
					 GenerateVariable("]("), GenerateVariable("."), GenerateVariable("/"),
					 GenerateVariable(production_rule_member_name_->This()), GenerateVariable("."),
					 GenerateVariable("md)")}));
			*production_rule_terminal_member_ = Variable_production_rule_terminal_member_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("["), GenerateVariable(production_rule_member_name_->This()),
					 GenerateVariable("]("), GenerateVariable("."), GenerateVariable("/"),
					 GenerateVariable("."), GenerateVariable("."), GenerateVariable("/Lexicon/"),
					 GenerateVariable(production_rule_member_name_->This()), GenerateVariable("."),
					 GenerateVariable("md)")}));
			*referencing_nonterminal_name_ =
				Variable_referencing_nonterminal_name_(this, std::vector<VariableBase*>({}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));
			*this_ = Variable_this_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("**["), GenerateVariable(nonterminal_name_->This()),
						   GenerateVariable("]("), GenerateVariable("."), GenerateVariable("/"),
						   GenerateVariable(nonterminal_name_->This()), GenerateVariable("."),
						   GenerateVariable("md)**")}));

			variables_.emplace_back(abstraction_);
			variables_.emplace_back(file_);
			variables_.emplace_back(inlined_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(nonterminal_name_);
			variables_.emplace_back(nonterminal_production_rule_);
			variables_.emplace_back(nonterminal_reference_);
			variables_.emplace_back(nonterminal_reference_section_);
			variables_.emplace_back(optional_nonterminal_reference_section_);
			variables_.emplace_back(production_rule_);
			variables_.emplace_back(production_rule_empty_member_);
			variables_.emplace_back(production_rule_member_);
			variables_.emplace_back(production_rule_member_name_);
			variables_.emplace_back(production_rule_nonterminal_member_);
			variables_.emplace_back(production_rule_terminal_member_);
			variables_.emplace_back(referencing_nonterminal_name_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
			variables_.emplace_back(this_);
		}

		virtual ~NonTerminalTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_DEAMERDOCUMENTATION_GRAMMAR_MARKDOWN_NONTERMINALTEMPLATE_h
