#ifndef DEAMER_TEMPLATES_CMAKE_SINGLE_LIB_DEFAULTDEAMERTEMPLATE_h
#define DEAMER_TEMPLATES_CMAKE_SINGLE_LIB_DEFAULTDEAMERTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace deamer::templates::cmake::single::lib
{
	/*!	\class DefaultDeamerTemplate
	 *
	 *	\brief Generates code for "DefaultDeamerTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class DefaultDeamerTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			CMAKE_VAR_INTRO_,
			cmake_package_name_,
			const_qualifier_,
			file_,
			languageName_,
			language_library_,
			language_library_legacy_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			optional_if_not_root_alias_target_,
			package_cmake_namespace_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,
			root_language_name_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char* ConvertEnumToName(
			::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				CMAKE_VAR_INTRO_: {
				return "CMAKE_VAR_INTRO";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				cmake_package_name_: {
				return "cmake_package_name";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				const_qualifier_: {
				return "const_qualifier";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::file_: {
				return "file";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				languageName_: {
				return "languageName";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				language_library_: {
				return "language_library";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				language_library_legacy_: {
				return "language_library_legacy";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				left_bracket_: {
				return "left_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				optional_if_not_root_alias_target_: {
				return "optional_if_not_root_alias_target";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				package_cmake_namespace_: {
				return "package_cmake_namespace";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				right_bracket_: {
				return "right_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				right_curly_bracket_: {
				return "right_curly_bracket";
			}

			case ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
				root_language_name_: {
				return "root_language_name";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type type =
				::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType scope_type =
				::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType
							  scope_type_,
						  bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;
			}

			VariableScope(const char* text,
						  ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType
							  scope_type_,
						  bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable,
						  ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType
							  scope_type_,
						  bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									ScopeType::Upper_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									ScopeType::Lower_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									ScopeType::Snake_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									ScopeType::Slash_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									ScopeType::DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(
				::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::ScopeType::Default_,
				true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ =
				new VariableScope(::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									  ScopeType::Variable_Field_,
								  true);
			VariableBase* variable_field_separator_ =
				new VariableScope("\n",
								  ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::
									  ScopeType::Variable_Field_Separator_,
								  true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_CMAKE_VAR_INTRO_ : public VariableScopes
		{
			static constexpr auto name = "CMAKE_VAR_INTRO_";

			Variable_CMAKE_VAR_INTRO_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					CMAKE_VAR_INTRO_;
			}

			virtual ~Variable_CMAKE_VAR_INTRO_() override = default;

			Variable_CMAKE_VAR_INTRO_(DefaultDeamerTemplate* defaultdeamertemplate_,
									  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					CMAKE_VAR_INTRO_;
			}

			Variable_CMAKE_VAR_INTRO_& operator=(const Variable_CMAKE_VAR_INTRO_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_cmake_package_name_ : public VariableScopes
		{
			static constexpr auto name = "cmake_package_name_";

			Variable_cmake_package_name_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					cmake_package_name_;
			}

			virtual ~Variable_cmake_package_name_() override = default;

			Variable_cmake_package_name_(DefaultDeamerTemplate* defaultdeamertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					cmake_package_name_;
			}

			Variable_cmake_package_name_& operator=(const Variable_cmake_package_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_const_qualifier_ : public VariableScopes
		{
			static constexpr auto name = "const_qualifier_";

			Variable_const_qualifier_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					const_qualifier_;
			}

			virtual ~Variable_const_qualifier_() override = default;

			Variable_const_qualifier_(DefaultDeamerTemplate* defaultdeamertemplate_,
									  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					const_qualifier_;
			}

			Variable_const_qualifier_& operator=(const Variable_const_qualifier_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(DefaultDeamerTemplate* defaultdeamertemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("# This file is auto-generated and auto-maintained"),
					 GenerateVariable("."),
					 GenerateVariable("\n# Please don't change code in this file, as new changes "
									  "will be discarded,\n# when Deamer regenerates the project"),
					 GenerateVariable("."),
					 GenerateVariable("\n#\n# If you want to contribute to Deamer"),
					 GenerateVariable("."),
					 GenerateVariable("\n# Please visit: https://github"),
					 GenerateVariable("."),
					 GenerateVariable(
						 "com/Deruago/theDeamerProject\n#\n# This file is part of the directory: "
						 "lib\n\n# All source and header files of this project"),
					 GenerateVariable("."),
					 GenerateVariable("\nfile(GLOB_RECURSE SOURCE_LIST \""),
					 GenerateVariable(defaultdeamertemplate_->CMAKE_VAR_INTRO_->This()),
					 GenerateVariable(defaultdeamertemplate_->languageName_->This()),
					 GenerateVariable("_SOURCE_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/lib/*"),
					 GenerateVariable("."),
					 GenerateVariable("cpp\")\nfile(GLOB_RECURSE HEADER_LIST \""),
					 GenerateVariable(defaultdeamertemplate_->CMAKE_VAR_INTRO_->This()),
					 GenerateVariable(defaultdeamertemplate_->languageName_->This()),
					 GenerateVariable("_SOURCE_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/include/*"),
					 GenerateVariable("."),
					 GenerateVariable("h\")\n\n# Root library extension\n"),
					 GenerateVariable(defaultdeamertemplate_->root_language_name_->This()),
					 GenerateVariable("_root_library_extend(\""),
					 GenerateVariable(defaultdeamertemplate_->languageName_->This()),
					 GenerateVariable("\" \""),
					 GenerateVariable(defaultdeamertemplate_->CMAKE_VAR_INTRO_->This()),
					 GenerateVariable(defaultdeamertemplate_->languageName_->This()),
					 GenerateVariable("_SOURCE_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/extern\" \""),
					 GenerateVariable(defaultdeamertemplate_->CMAKE_VAR_INTRO_->This()),
					 GenerateVariable(defaultdeamertemplate_->languageName_->This()),
					 GenerateVariable("_SOURCE_DIR"),
					 GenerateVariable("}"),
					 GenerateVariable("/include\" \"$"),
					 GenerateVariable("{"),
					 GenerateVariable("SOURCE_LIST"),
					 GenerateVariable("}"),
					 GenerateVariable("\")\n\n"),
					 GenerateVariable(
						 defaultdeamertemplate_->optional_if_not_root_alias_target_->This())}));
				Content_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("DefaultDeamer")}));
				File_name_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("deamer::templates::cmake::single::lib")}));
				Namespace_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type =
					::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_languageName_ : public VariableScopes
		{
			static constexpr auto name = "languageName_";

			Variable_languageName_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					languageName_;
			}

			virtual ~Variable_languageName_() override = default;

			Variable_languageName_(DefaultDeamerTemplate* defaultdeamertemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					languageName_;
			}

			Variable_languageName_& operator=(const Variable_languageName_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_library_ : public VariableScopes
		{
			static constexpr auto name = "language_library_";

			Variable_language_library_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					language_library_;
			}

			virtual ~Variable_language_library_() override = default;

			Variable_language_library_(DefaultDeamerTemplate* defaultdeamertemplate_,
									   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					language_library_;
			}

			Variable_language_library_& operator=(const Variable_language_library_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_library_legacy_ : public VariableScopes
		{
			static constexpr auto name = "language_library_legacy_";

			Variable_language_library_legacy_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					language_library_legacy_;
			}

			virtual ~Variable_language_library_legacy_() override = default;

			Variable_language_library_legacy_(DefaultDeamerTemplate* defaultdeamertemplate_,
											  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					language_library_legacy_;
			}

			Variable_language_library_legacy_&
			operator=(const Variable_language_library_legacy_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_optional_if_not_root_alias_target_ : public VariableScopes
		{
			static constexpr auto name = "optional_if_not_root_alias_target_";

			Variable_optional_if_not_root_alias_target_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					optional_if_not_root_alias_target_;
			}

			virtual ~Variable_optional_if_not_root_alias_target_() override = default;

			Variable_optional_if_not_root_alias_target_(
				DefaultDeamerTemplate* defaultdeamertemplate_,
				const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					optional_if_not_root_alias_target_;
			}

			Variable_optional_if_not_root_alias_target_&
			operator=(const Variable_optional_if_not_root_alias_target_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_package_cmake_namespace_ : public VariableScopes
		{
			static constexpr auto name = "package_cmake_namespace_";

			Variable_package_cmake_namespace_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					package_cmake_namespace_;
			}

			virtual ~Variable_package_cmake_namespace_() override = default;

			Variable_package_cmake_namespace_(DefaultDeamerTemplate* defaultdeamertemplate_,
											  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					package_cmake_namespace_;
			}

			Variable_package_cmake_namespace_&
			operator=(const Variable_package_cmake_namespace_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(DefaultDeamerTemplate* defaultdeamertemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_root_language_name_ : public VariableScopes
		{
			static constexpr auto name = "root_language_name_";

			Variable_root_language_name_() : VariableScopes()
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					root_language_name_;
			}

			virtual ~Variable_root_language_name_() override = default;

			Variable_root_language_name_(DefaultDeamerTemplate* defaultdeamertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::cmake::single::lib::DefaultDeamerTemplate::Type::
					root_language_name_;
			}

			Variable_root_language_name_& operator=(const Variable_root_language_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. DefaultDeamerTemplate.member = "auto-generated";
		Variable_CMAKE_VAR_INTRO_* CMAKE_VAR_INTRO_ = new Variable_CMAKE_VAR_INTRO_();
		Variable_cmake_package_name_* cmake_package_name_ = new Variable_cmake_package_name_();
		Variable_const_qualifier_* const_qualifier_ = new Variable_const_qualifier_();
		Variable_file_* file_ = new Variable_file_();
		Variable_languageName_* languageName_ = new Variable_languageName_();
		Variable_language_library_* language_library_ = new Variable_language_library_();
		Variable_language_library_legacy_* language_library_legacy_ =
			new Variable_language_library_legacy_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_optional_if_not_root_alias_target_* optional_if_not_root_alias_target_ =
			new Variable_optional_if_not_root_alias_target_();
		Variable_package_cmake_namespace_* package_cmake_namespace_ =
			new Variable_package_cmake_namespace_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();
		Variable_root_language_name_* root_language_name_ = new Variable_root_language_name_();

	public:
		DefaultDeamerTemplate()
		{
			*CMAKE_VAR_INTRO_ = Variable_CMAKE_VAR_INTRO_(
				this, std::vector<VariableBase*>({GenerateVariable("$"), GenerateVariable("{")}));
			*cmake_package_name_ = Variable_cmake_package_name_(
				this, std::vector<VariableBase*>({GenerateVariable(root_language_name_->This())}));
			*const_qualifier_ = Variable_const_qualifier_(
				this, std::vector<VariableBase*>({GenerateVariable("const")}));
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*languageName_ = Variable_languageName_(this, std::vector<VariableBase*>({}));
			*language_library_ = Variable_language_library_(
				this, std::vector<VariableBase*>({GenerateVariable(cmake_package_name_->This())}));
			*language_library_legacy_ = Variable_language_library_legacy_(
				this, std::vector<VariableBase*>({GenerateVariable(root_language_name_->This()),
												  GenerateVariable("_static_library")}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*optional_if_not_root_alias_target_ = Variable_optional_if_not_root_alias_target_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("add_library("), GenerateVariable(languageName_->This()),
					 GenerateVariable("_static_library ALIAS "),
					 GenerateVariable(language_library_->This()), GenerateVariable(")")}));
			*package_cmake_namespace_ = Variable_package_cmake_namespace_(
				this, std::vector<VariableBase*>({GenerateVariable(cmake_package_name_->This())}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));
			*root_language_name_ =
				Variable_root_language_name_(this, std::vector<VariableBase*>({}));

			variables_.emplace_back(CMAKE_VAR_INTRO_);
			variables_.emplace_back(cmake_package_name_);
			variables_.emplace_back(const_qualifier_);
			variables_.emplace_back(file_);
			variables_.emplace_back(languageName_);
			variables_.emplace_back(language_library_);
			variables_.emplace_back(language_library_legacy_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(optional_if_not_root_alias_target_);
			variables_.emplace_back(package_cmake_namespace_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
			variables_.emplace_back(root_language_name_);
		}

		virtual ~DefaultDeamerTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_CMAKE_SINGLE_LIB_DEFAULTDEAMERTEMPLATE_h
