name: CMake

on: [push]

env:
   BUILD_TYPE: Release

jobs:
  build:
    name: Build source code and run tests.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      shell: bash
      run: sudo python ${{github.workspace}}/installer.py -external-only -no-confirm-with-enter

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEAMER_BUILD_TESTS=ON

    - name: Build production code
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target Deamer

    - name: Build tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target deamer_unit_tests
      
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: Deamer/tests/deamer_unit_tests
     

