#ifndef DEAMER_TEMPLATES_TOOL_DEAMERDEFAULTAPPLICATION_TOKENVIEWER_TOKENVIEWERTEMPLATE_h
#define DEAMER_TEMPLATES_TOOL_DEAMERDEFAULTAPPLICATION_TOKENVIEWER_TOKENVIEWERTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace deamer::templates::tool::deamerdefaultapplication::tokenviewer
{
	/*!	\class TokenViewerTemplate
	 *
	 *	\brief Generates code for "TokenViewerTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class TokenViewerTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			class_name_,
			file_,
			language_name_,
			language_name_underscore_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			lexer_,
			parser_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char*
		ConvertEnumToName(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
							  TokenViewerTemplate::Type enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::class_name_: {
				return "class_name";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::file_: {
				return "file";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::language_name_: {
				return "language_name";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::language_name_underscore_: {
				return "language_name_underscore";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::left_bracket_: {
				return "left_bracket";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::lexer_: {
				return "lexer";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::parser_: {
				return "parser";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::right_bracket_: {
				return "right_bracket";
			}

			case ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
				TokenViewerTemplate::Type::right_curly_bracket_: {
				return "right_curly_bracket";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::deamer::templates::tool::deamerdefaultapplication::tokenviewer::TokenViewerTemplate::
				Type type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::deamer::templates::tool::deamerdefaultapplication::tokenviewer::TokenViewerTemplate::
				ScopeType scope_type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
							  TokenViewerTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::Scope;
			}

			VariableScope(const char* text,
						  ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
							  TokenViewerTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable,
						  ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
							  TokenViewerTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									TokenViewerTemplate::ScopeType::Upper_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									TokenViewerTemplate::ScopeType::Lower_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									TokenViewerTemplate::ScopeType::Snake_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									TokenViewerTemplate::ScopeType::Slash_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									TokenViewerTemplate::ScopeType::DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ =
				new VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									  TokenViewerTemplate::ScopeType::Default_,
								  true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ =
				new VariableScope(::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									  TokenViewerTemplate::ScopeType::Variable_Field_,
								  true);
			VariableBase* variable_field_separator_ =
				new VariableScope("\n",
								  ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
									  TokenViewerTemplate::ScopeType::Variable_Field_Separator_,
								  true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_class_name_ : public VariableScopes
		{
			static constexpr auto name = "class_name_";

			Variable_class_name_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::class_name_;
			}

			virtual ~Variable_class_name_() override = default;

			Variable_class_name_(TokenViewerTemplate* tokenviewertemplate_,
								 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::class_name_;
			}

			Variable_class_name_& operator=(const Variable_class_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(TokenViewerTemplate* tokenviewertemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable("#include \""),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("/"),
					 GenerateVariable(tokenviewertemplate_->lexer_->This()),
					 GenerateVariable("/Lexer"),
					 GenerateVariable("."),
					 GenerateVariable("h\"\n#include \""),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("/"),
					 GenerateVariable(tokenviewertemplate_->parser_->This()),
					 GenerateVariable("/Parser"),
					 GenerateVariable("."),
					 GenerateVariable("h\"\n#include \""),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("/Ast/Relation/NodeEnumToText"),
					 GenerateVariable("."),
					 GenerateVariable("h\"\n#include <fstream>\n#include <iostream>\n#include "
									  "<sstream>\n#include <vector>\n\nstd::string "
									  "ReadInFile(const std::string& file)\n"),
					 GenerateVariable("{"),
					 GenerateVariable(
						 "\n\tconst std::ifstream inputFile(file);\n\n\tstd::ostringstream "
						 "sstr;\n\tsstr << inputFile"),
					 GenerateVariable("."),
					 GenerateVariable("rdbuf();\n\n\tstd::string input = sstr"),
					 GenerateVariable("."),
					 GenerateVariable("str();\n\n\treturn input;\n"),
					 GenerateVariable("}"),
					 GenerateVariable("\n\nint main(int argc, const char* argv[])\n"),
					 GenerateVariable("{"),
					 GenerateVariable("\n\tstd::vector<std::string> filenames = "),
					 GenerateVariable("{"),
					 GenerateVariable("\""),
					 GenerateVariable("."),
					 GenerateVariable("/test"),
					 GenerateVariable("."),
					 GenerateVariable("txt\""),
					 GenerateVariable("}"),
					 GenerateVariable(";\n\n\tfor (auto i = 1; i < argc; i++)\n\t"),
					 GenerateVariable("{"),
					 GenerateVariable("\n\t\tfilenames"),
					 GenerateVariable("."),
					 GenerateVariable("push_back(argv[1]);\n\t"),
					 GenerateVariable("}"),
					 GenerateVariable("\n\n\tfor (const auto& filename : filenames)\n\t"),
					 GenerateVariable("{"),
					 GenerateVariable(
						 "\n\t\tstd::string text = ReadInFile(filename);\n\n\t\tstd::cout << "
						 "\"File: \" << filename << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\tstd::cout << text << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\n\t\tauto lexer = "),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("::lexer::Lexer();\n\t\tauto tokens = lexer"),
					 GenerateVariable("."),
					 GenerateVariable("Tokenize(text);\n\t\t"),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("::parser::Parser();\n\n\t\tstd::cout << \"Tokens:"),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\tfor (auto token : tokens)\n\t\t"),
					 GenerateVariable("{"),
					 GenerateVariable("\n\t\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("tTokenName: \" << "),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("::ast::relation::ConvertEnumToText(static_cast<"),
					 GenerateVariable(tokenviewertemplate_->language_name_->This()),
					 GenerateVariable("::ast::Type>(token->Type)) << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("t"),
					 GenerateVariable("\\"),
					 GenerateVariable("tValue: \" << token->Value << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("t"),
					 GenerateVariable("\\"),
					 GenerateVariable("tLine: \" << std::to_string(token->LineNumber) << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("t"),
					 GenerateVariable("\\"),
					 GenerateVariable("tColumn: \" << std::to_string(token->ColumnNumber) << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\t\t\tstd::cout << \""),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\n\t\t\tdelete token;\n\t\t"),
					 GenerateVariable("}"),
					 GenerateVariable("\n\t"),
					 GenerateVariable("}"),
					 GenerateVariable("\n\n\tstd::cout << \"Compilation succeeded!"),
					 GenerateVariable("\\"),
					 GenerateVariable("n\";\n\treturn 0;\n"),
					 GenerateVariable("}")}));
				Content_->type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable(tokenviewertemplate_->class_name_->This())}));
				File_name_->type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable(
						"deamer::templates::tool::deamerdefaultapplication::tokenviewer")}));
				Namespace_->type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type = ::deamer::templates::tool::deamerdefaultapplication::
					tokenviewer::TokenViewerTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_language_name_ : public VariableScopes
		{
			static constexpr auto name = "language_name_";

			Variable_language_name_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::language_name_;
			}

			virtual ~Variable_language_name_() override = default;

			Variable_language_name_(TokenViewerTemplate* tokenviewertemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::language_name_;
			}

			Variable_language_name_& operator=(const Variable_language_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_name_underscore_ : public VariableScopes
		{
			static constexpr auto name = "language_name_underscore_";

			Variable_language_name_underscore_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::language_name_underscore_;
			}

			virtual ~Variable_language_name_underscore_() override = default;

			Variable_language_name_underscore_(TokenViewerTemplate* tokenviewertemplate_,
											   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::language_name_underscore_;
			}

			Variable_language_name_underscore_&
			operator=(const Variable_language_name_underscore_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(TokenViewerTemplate* tokenviewertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(TokenViewerTemplate* tokenviewertemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(TokenViewerTemplate* tokenviewertemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_lexer_ : public VariableScopes
		{
			static constexpr auto name = "lexer_";

			Variable_lexer_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::lexer_;
			}

			virtual ~Variable_lexer_() override = default;

			Variable_lexer_(TokenViewerTemplate* tokenviewertemplate_,
							const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::lexer_;
			}

			Variable_lexer_& operator=(const Variable_lexer_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_parser_ : public VariableScopes
		{
			static constexpr auto name = "parser_";

			Variable_parser_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::parser_;
			}

			virtual ~Variable_parser_() override = default;

			Variable_parser_(TokenViewerTemplate* tokenviewertemplate_,
							 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::parser_;
			}

			Variable_parser_& operator=(const Variable_parser_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(TokenViewerTemplate* tokenviewertemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(TokenViewerTemplate* tokenviewertemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(TokenViewerTemplate* tokenviewertemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::deamer::templates::tool::deamerdefaultapplication::tokenviewer::
					TokenViewerTemplate::Type::right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. TokenViewerTemplate.member = "auto-generated";
		Variable_class_name_* class_name_ = new Variable_class_name_();
		Variable_file_* file_ = new Variable_file_();
		Variable_language_name_* language_name_ = new Variable_language_name_();
		Variable_language_name_underscore_* language_name_underscore_ =
			new Variable_language_name_underscore_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_lexer_* lexer_ = new Variable_lexer_();
		Variable_parser_* parser_ = new Variable_parser_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();

	public:
		TokenViewerTemplate()
		{
			*class_name_ = Variable_class_name_(
				this, std::vector<VariableBase*>({GenerateVariable("TokenViewer")}));
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*language_name_ = Variable_language_name_(this, std::vector<VariableBase*>({}));
			*language_name_underscore_ = Variable_language_name_underscore_(
				this, std::vector<VariableBase*>({GenerateVariable(language_name_->Underscore())}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*lexer_ = Variable_lexer_(this, std::vector<VariableBase*>({GenerateVariable("Flex")}));
			*parser_ =
				Variable_parser_(this, std::vector<VariableBase*>({GenerateVariable("Bison")}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));

			variables_.emplace_back(class_name_);
			variables_.emplace_back(file_);
			variables_.emplace_back(language_name_);
			variables_.emplace_back(language_name_underscore_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(lexer_);
			variables_.emplace_back(parser_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
		}

		virtual ~TokenViewerTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DEAMER_TEMPLATES_TOOL_DEAMERDEFAULTAPPLICATION_TOKENVIEWER_TOKENVIEWERTEMPLATE_h
